- hosts: localhost
  become: false
  vars_files:
    - vars.yml
  roles:
    - { role: multipass/v5 }

- hosts: all
  become: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  roles:
    - { role: microk8s/v4 }
    - nginx